//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex
    {
        public decimal antal { get; set; }
        public string ArtBeskr { get; set; }
        public Nullable<decimal> ArtKalkBer { get; set; }
        public string ArtNr { get; set; }
        public string ArtProdKonto { get; set; }
        public string ArtSerieing { get; set; }
        public string artserienr { get; set; }
        public string BatchId { get; set; }
        public Nullable<int> bestnr { get; set; }
        public string BestRkgNr { get; set; }
        public string DummyUniqueId { get; set; }
        public string Edit { get; set; }
        public string EditExt { get; set; }
        public string EnhetsKod { get; set; }
        public Nullable<short> EventRpKod { get; set; }
        public System.DateTime ExLevDat { get; set; }
        public string exRadText { get; set; }
        public Nullable<int> ExtKostnadLista { get; set; }
        public decimal FaktMoms { get; set; }
        public Nullable<int> FaktNr { get; set; }
        public Nullable<int> FaktNrOrg { get; set; }
        public Nullable<int> FaktRadNr { get; set; }
        public Nullable<int> FaktRadNrOrg { get; set; }
        public decimal FaktRadSumma { get; set; }
        public decimal FaktRadSummaInklMoms { get; set; }
        public string Faktureras { get; set; }
        public short ForetagKod { get; set; }
        public string FtgNr { get; set; }
        public string K4 { get; set; }
        public string K5 { get; set; }
        public string K6 { get; set; }
        public string K7 { get; set; }
        public string KostBar { get; set; }
        public string KostStalleKod { get; set; }
        public string KtoNr { get; set; }
        public string KundBetalareNr { get; set; }
        public string KundNr { get; set; }
        public double KundRabatt { get; set; }
        public string LagPlats { get; set; }
        public string LagStalle { get; set; }
        public string Loneart { get; set; }
        public double markup { get; set; }
        public Nullable<short> MomsKod { get; set; }
        public string OffNr { get; set; }
        public string OKtoInvoice { get; set; }
        public string ole1 { get; set; }
        public Nullable<int> ordernr { get; set; }
        public string OrdLevPlats1 { get; set; }
        public double OrdRabatt { get; set; }
        public Nullable<short> Period { get; set; }
        public string PersSign { get; set; }
        public string PersSign2 { get; set; }
        public Nullable<decimal> pris { get; set; }
        public Nullable<short> prislista { get; set; }
        public string ProjCode { get; set; }
        public double Rabatt1 { get; set; }
        public double Rabatt2 { get; set; }
        public double Rabatt3 { get; set; }
        public Nullable<int> RadPos { get; set; }
        public Nullable<int> RadPos1 { get; set; }
        public Nullable<int> RadPos2 { get; set; }
        public Nullable<short> RedovisnAr { get; set; }
        public System.DateTime RegDat { get; set; }
        public string RowCreatedBy { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string RowUpdatedBy { get; set; }
        public Nullable<System.DateTime> RowUpdatedDt { get; set; }
        public string StrDateTime { get; set; }
        public Nullable<int> Tidrapportnr { get; set; }
        public string valkod { get; set; }
        public decimal ValKurs { get; set; }
        public decimal vb_pris { get; set; }
        public decimal VbFaktMoms { get; set; }
        public Nullable<short> Veckonr { get; set; }
        public Nullable<int> Vernr { get; set; }
        public Nullable<int> WorkFaktNr { get; set; }
        public Nullable<int> WorkFaktNrOrg { get; set; }
        public double q_ex_antalanstalld { get; set; }
        public string q_hrp_guiid { get; set; }
        public Nullable<short> q_reimburse_employee { get; set; }
        public Nullable<short> q_ex_reimbursedinvernr { get; set; }
        public Nullable<short> ICTRuleNumber { get; set; }
        public Nullable<short> IntrnCoNoOrigin { get; set; }
        public Nullable<int> InvRowNo { get; set; }
        public Nullable<short> LagTransTyp { get; set; }
        public Nullable<short> No_trigger_exec { get; set; }
        public string RowUpdatedCols { get; set; }
        public string q_ex_forslag_kb { get; set; }
        public string q_ex_forslag_koststallekod { get; set; }
        public string q_ex_forslag_ktonr { get; set; }
        public string q_ex_forslag_k4 { get; set; }
        public string q_ex_forslag_k5 { get; set; }
        public Nullable<int> q_ex_reimbursedyear { get; set; }
        public string AddToProjCost { get; set; }
        public string CreatedByDbObject { get; set; }
        public int PdmCount { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public Nullable<System.DateTime> RowCreatedUTCDT { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> RptUnitNo { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public Nullable<short> VAT_Type { get; set; }
        public decimal VolymRabatt { get; set; }
    }
}
