//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr
    {
        public Nullable<short> Aktivitet { get; set; }
        public Nullable<short> Aktstatus { get; set; }
        public Nullable<int> AoNr { get; set; }
        public Nullable<int> AoPos { get; set; }
        public string ArbetsLag { get; set; }
        public string ArtNr { get; set; }
        public string ArtSerieNr { get; set; }
        public string Avbcode { get; set; }
        public Nullable<int> BestNr { get; set; }
        public Nullable<int> BestRadNr { get; set; }
        public Nullable<int> BestRestNr { get; set; }
        public string CreatedByDBObject { get; set; }
        public string DummyUniqueId { get; set; }
        public string Edit { get; set; }
        public string Editext { get; set; }
        public string EditInt { get; set; }
        public Nullable<short> EventKod1 { get; set; }
        public string EventNote { get; set; }
        public Nullable<int> EventNr { get; set; }
        public Nullable<System.DateTime> EventPlDat { get; set; }
        public Nullable<System.DateTime> EventPlTime { get; set; }
        public Nullable<System.DateTime> EventStartDat { get; set; }
        public Nullable<System.DateTime> EventSTartTime { get; set; }
        public decimal EventTimant2 { get; set; }
        public string Faktureras { get; set; }
        public string FlodesGrupp { get; set; }
        public short ForetagKod { get; set; }
        public Nullable<short> FtgKontaktNr { get; set; }
        public string FtgNr { get; set; }
        public string Hrblock { get; set; }
        public string InkHandl { get; set; }
        public string K4 { get; set; }
        public string K5 { get; set; }
        public string K6 { get; set; }
        public string K7 { get; set; }
        public Nullable<decimal> kalkkostMantim { get; set; }
        public string KostBar { get; set; }
        public string KostStalleKod { get; set; }
        public Nullable<System.DateTime> KvittDatum { get; set; }
        public int LopNr { get; set; }
        public string OffNr { get; set; }
        public string ole1 { get; set; }
        public string ole2 { get; set; }
        public Nullable<int> OpNr { get; set; }
        public Nullable<int> OrderNr { get; set; }
        public Nullable<int> OrdRadNr { get; set; }
        public Nullable<int> OrdRadNrStrPos { get; set; }
        public int PdmCount { get; set; }
        public string PersSign { get; set; }
        public Nullable<short> PersSignNr { get; set; }
        public string PlanAnsv { get; set; }
        public string PlanId { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.DateTime> PlannedEndTime { get; set; }
        public string PlanUtford { get; set; }
        public Nullable<System.DateTime> PrjLovLevDat { get; set; }
        public string ProjCode { get; set; }
        public Nullable<int> ProjectPriority { get; set; }
        public double projkvartid { get; set; }
        public double projnerltid { get; set; }
        public Nullable<System.DateTime> Projrevenddat { get; set; }
        public Nullable<System.DateTime> Projrevstartdat { get; set; }
        public Nullable<int> ProspektId { get; set; }
        public Nullable<int> RadPos { get; set; }
        public Nullable<int> radpos2 { get; set; }
        public Nullable<short> Redovisnar { get; set; }
        public System.DateTime RegDat { get; set; }
        public Nullable<System.DateTime> regtime { get; set; }
        public string RowCreatedBy { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string RowUpdatedBy { get; set; }
        public Nullable<System.DateTime> RowUpdatedDt { get; set; }
        public string Sender { get; set; }
        public string StrDateTime { get; set; }
        public Nullable<short> TidKod { get; set; }
        public Nullable<short> TjKod { get; set; }
        public Nullable<short> verksamhet { get; set; }
        public decimal q_prj_prisperh { get; set; }
        public Nullable<short> q_hr_supress_externalcomment { get; set; }
        public string AutoConnect { get; set; }
        public string BelongSign { get; set; }
        public string EventAvslutsKrav { get; set; }
        public Nullable<short> ICTRuleNumber { get; set; }
        public Nullable<short> IntrnCoNoOrigin { get; set; }
        public Nullable<int> kampnr { get; set; }
        public Nullable<short> No_trigger_exec { get; set; }
        public string RowUpdatedCols { get; set; }
        public string sent_2_Outl_cal { get; set; }
        public Nullable<short> ActvyGrpsId { get; set; }
        public decimal AllcdTime { get; set; }
        public decimal Antal { get; set; }
        public decimal ArtKalkBer { get; set; }
        public short ArtKalkPer { get; set; }
        public Nullable<short> AssetID { get; set; }
        public string AutoConnect_OtherUser { get; set; }
        public string EstimatorOffNr { get; set; }
        public Nullable<short> EstimatorOffRadNr { get; set; }
        public Nullable<short> EventRpKod { get; set; }
        public string FixedDescr { get; set; }
        public Nullable<short> IterationID { get; set; }
        public decimal KundRabatt { get; set; }
        public string MainActivity { get; set; }
        public string MarkedAsMain { get; set; }
        public Nullable<double> MarkUpArtKalkBer { get; set; }
        public Nullable<double> MarkUpKalkKostManTim { get; set; }
        public string MileStone { get; set; }
        public string MileStoneID { get; set; }
        public Nullable<int> OffRadNr { get; set; }
        public Nullable<int> OrderNrServ { get; set; }
        public Nullable<int> OrdRadNrServ { get; set; }
        public Nullable<short> Perskategori { get; set; }
        public decimal PlanActvyCostBCU { get; set; }
        public decimal PlanActvyCostFCU { get; set; }
        public decimal PlanActvyRevenueBCU { get; set; }
        public decimal PlanActvyRevenueFCU { get; set; }
        public decimal PlannedAllcdTime { get; set; }
        public decimal PriceActivityBCU { get; set; }
        public decimal PriceActivityFCU { get; set; }
        public decimal Pris { get; set; }
        public decimal rabatt1 { get; set; }
        public decimal rabatt2 { get; set; }
        public decimal rabatt3 { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public string ReqID { get; set; }
        public Nullable<System.DateTime> RowCreatedUTCDT { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public string ValKod { get; set; }
        public decimal ValKurs { get; set; }
        public decimal vb_pris { get; set; }
        public decimal VolymRabatt { get; set; }
    }
}
