//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrp
    {
        public string Aktavsl { get; set; }
        public Nullable<short> Aktivitet { get; set; }
        public Nullable<int> AoNr { get; set; }
        public Nullable<int> AoPos { get; set; }
        public string ArtNr { get; set; }
        public string ArtSerieNr { get; set; }
        public Nullable<int> BestNr { get; set; }
        public string CreatedByDBObject { get; set; }
        public Nullable<short> DebKod { get; set; }
        public string dokdir { get; set; }
        public string Edit { get; set; }
        public string editext { get; set; }
        public string EventNote { get; set; }
        public System.DateTime EventRpEndDat { get; set; }
        public Nullable<short> EventRpKod { get; set; }
        public System.DateTime EventRpTime { get; set; }
        public decimal EventTimant2 { get; set; }
        public string Exec_Time_Log_String { get; set; }
        public double ExecutionTime { get; set; }
        public Nullable<int> FaktNr { get; set; }
        public Nullable<int> FaktNrOrg { get; set; }
        public Nullable<int> FaktRadnr { get; set; }
        public Nullable<int> FaktRadNrOrg { get; set; }
        public string Faktureras { get; set; }
        public Nullable<short> FardigGrad { get; set; }
        public short ForetagKod { get; set; }
        public Nullable<short> FtgKontaktNr { get; set; }
        public string FtgNr { get; set; }
        public string Hrpblock { get; set; }
        public System.DateTime Ins_DT_MilliSecond { get; set; }
        public Nullable<int> InterndebJournal { get; set; }
        public Nullable<decimal> Internpris { get; set; }
        public Nullable<System.DateTime> Jeeves_Init_Insert_Enter { get; set; }
        public Nullable<System.DateTime> Jeeves_Init_Insert_PreIns { get; set; }
        public string K4 { get; set; }
        public string K5 { get; set; }
        public string K6 { get; set; }
        public string K7 { get; set; }
        public Nullable<decimal> KalkKostManTim { get; set; }
        public Nullable<int> KampNr { get; set; }
        public string KampResponsKlar { get; set; }
        public Nullable<short> KampSvarsKod { get; set; }
        public string KortNotering { get; set; }
        public string KostBar { get; set; }
        public string KostStalleKod { get; set; }
        public string KtoNr { get; set; }
        public string LevNr { get; set; }
        public string Loneart { get; set; }
        public int LopNr { get; set; }
        public string MasterProjCode { get; set; }
        public decimal NedlagdTid { get; set; }
        public short No_Trigger_Exec { get; set; }
        public string OffNr { get; set; }
        public string OKtoInvoice { get; set; }
        public string ole1 { get; set; }
        public string ole2 { get; set; }
        public Nullable<int> OpNr { get; set; }
        public Nullable<int> OrderNr { get; set; }
        public Nullable<int> OrdRadNr { get; set; }
        public Nullable<int> OrdRadNrStrPos { get; set; }
        public Nullable<System.DateTime> p_utskr_dat { get; set; }
        public int PdmCount { get; set; }
        public string pdmdummyuniqueid { get; set; }
        public Nullable<short> Period { get; set; }
        public Nullable<short> perskategori { get; set; }
        public string PersSign { get; set; }
        public Nullable<short> PersSignNr { get; set; }
        public string PlanId { get; set; }
        public string PlanUtford { get; set; }
        public Nullable<decimal> pris { get; set; }
        public string PrKostStalleKod { get; set; }
        public string ProjCode { get; set; }
        public Nullable<int> ProjKonterJournal { get; set; }
        public double ProjKvarTid { get; set; }
        public Nullable<int> ProspektId { get; set; }
        public System.DateTime QQ_Ins_Trg_Start { get; set; }
        public Nullable<int> RadPos { get; set; }
        public int radpos2 { get; set; }
        public Nullable<short> Redovisnar { get; set; }
        public System.DateTime RegDat { get; set; }
        public Nullable<System.DateTime> regtime { get; set; }
        public string RowCreatedBy { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string RowUpdatedBy { get; set; }
        public Nullable<System.DateTime> RowUpdatedDt { get; set; }
        public Nullable<short> SparrKostnadskontering { get; set; }
        public string StrDateTime { get; set; }
        public string StrDateTimehr { get; set; }
        public Nullable<short> tidkod { get; set; }
        public Nullable<int> TidrapportNr { get; set; }
        public string TjansteKonto { get; set; }
        public string valkod { get; set; }
        public decimal ValKurs { get; set; }
        public decimal vb_pris { get; set; }
        public Nullable<short> Veckonr { get; set; }
        public Nullable<short> verksamhet { get; set; }
        public Nullable<int> WorkFaktNr { get; set; }
        public Nullable<int> WorkFaktNrOrg { get; set; }
        public string q_hrp_guiid { get; set; }
        public Nullable<short> q_hrp_delayinvoice { get; set; }
        public string q_hrp_commentcust_prio { get; set; }
        public decimal Antal { get; set; }
        public string ExtOrderNr { get; set; }
        public Nullable<short> ICTRuleNumber { get; set; }
        public Nullable<short> IntrnCoNoOrigin { get; set; }
        public Nullable<int> InvRowNo { get; set; }
        public string PrKostBar { get; set; }
        public string ReturSedelSkapad { get; set; }
        public string RowUpdatedCols { get; set; }
        public Nullable<short> TimeApprovedStatus { get; set; }
        public string q_hrp_subproject_prio { get; set; }
        public Nullable<short> q_hrp_highattention { get; set; }
        public string AttRTimeType { get; set; }
        public string ConnDummyUniqueID { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public string ReqID { get; set; }
        public Nullable<System.DateTime> RowCreatedUTCDT { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public decimal rabatt { get; set; }
    }
}
