//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prj
    {
        public decimal AntalAttTillverka { get; set; }
        public string ArtNr { get; set; }
        public Nullable<short> Avtalskod { get; set; }
        public Nullable<int> BestNr { get; set; }
        public Nullable<System.DateTime> BestOEDatum { get; set; }
        public Nullable<int> BestRadNr { get; set; }
        public Nullable<int> BestRestNr { get; set; }
        public Nullable<decimal> BestValue { get; set; }
        public Nullable<short> CompanyType { get; set; }
        public Nullable<System.DateTime> DatPrjFom { get; set; }
        public Nullable<System.DateTime> DatPrjTom { get; set; }
        public string Edit { get; set; }
        public string EditInkExt { get; set; }
        public Nullable<decimal> FaktInbBel { get; set; }
        public Nullable<decimal> FaktRestBel { get; set; }
        public Nullable<decimal> FaktTotMMoms { get; set; }
        public Nullable<decimal> FaktTotUMoms { get; set; }
        public Nullable<short> FardigGrad { get; set; }
        public string FarKonterasManuellt { get; set; }
        public string FarKonterasPa { get; set; }
        public Nullable<decimal> FastprisKost { get; set; }
        public short ForetagKod { get; set; }
        public string FtgNr { get; set; }
        public string InkAnsv { get; set; }
        public string InkHandl { get; set; }
        public Nullable<System.DateTime> InvFromDate { get; set; }
        public Nullable<System.DateTime> InvToDate { get; set; }
        public string K4 { get; set; }
        public string k4grupp { get; set; }
        public string K5 { get; set; }
        public string K5Grupp { get; set; }
        public string K6 { get; set; }
        public string K6Grupp { get; set; }
        public string K7 { get; set; }
        public string K7Grupp { get; set; }
        public string K8Grupp { get; set; }
        public string KBarGrupp { get; set; }
        public string Kostbar { get; set; }
        public string KostStalleKod { get; set; }
        public string KstGrupp { get; set; }
        public string KtoGrupp { get; set; }
        public string LevNr { get; set; }
        public Nullable<short> LevPlanStatus { get; set; }
        public Nullable<decimal> LrFaktBelBas { get; set; }
        public string MasterProjCode { get; set; }
        public Nullable<short> No_Trigger_Exec { get; set; }
        public string OffNr { get; set; }
        public string OKtoInvoice { get; set; }
        public string ole1 { get; set; }
        public string ole2 { get; set; }
        public Nullable<decimal> OrdSum { get; set; }
        public double Palagg { get; set; }
        public Nullable<decimal> PalaggBelopp { get; set; }
        public double PBeranttim { get; set; }
        public Nullable<decimal> PBerIntakt { get; set; }
        public Nullable<decimal> PBerKostnad { get; set; }
        public Nullable<System.DateTime> PBerSlutdat { get; set; }
        public Nullable<decimal> PBokfIntakt { get; set; }
        public Nullable<decimal> PBokfKostnad { get; set; }
        public int PdmCount { get; set; }
        public Nullable<short> Period { get; set; }
        public string PersSign { get; set; }
        public Nullable<decimal> PForlustriskAvsattning { get; set; }
        public string PlanAnsv { get; set; }
        public string PlannedProject { get; set; }
        public string PrjAccountPart { get; set; }
        public string PrjLittera { get; set; }
        public short Proj_Resultat_Balans { get; set; }
        public string ProjAnsv { get; set; }
        public string ProjBlock { get; set; }
        public string ProjCode { get; set; }
        public string ProjDescr { get; set; }
        public Nullable<int> ProjectPriority { get; set; }
        public Nullable<System.DateTime> ProjEndDat { get; set; }
        public Nullable<short> ProjInit { get; set; }
        public decimal ProjKost { get; set; }
        public double ProjKvarTid { get; set; }
        public double ProjNerlTid { get; set; }
        public Nullable<System.DateTime> ProjNextInvDate { get; set; }
        public Nullable<System.DateTime> Projrevenddat { get; set; }
        public Nullable<System.DateTime> Projrevstartdat { get; set; }
        public Nullable<System.DateTime> ProjStartDat { get; set; }
        public Nullable<short> ProjStatKod { get; set; }
        public string ProjTran2BalansId { get; set; }
        public Nullable<short> ProjType { get; set; }
        public Nullable<decimal> PUpparbIntakt { get; set; }
        public Nullable<decimal> PUpparbKostnad { get; set; }
        public Nullable<decimal> PUrspIntakt { get; set; }
        public Nullable<decimal> PUrspKostnad { get; set; }
        public Nullable<decimal> PVinstavraknat { get; set; }
        public Nullable<short> RedovisnAr { get; set; }
        public System.DateTime RegDat { get; set; }
        public Nullable<decimal> RestBelFakt { get; set; }
        public Nullable<System.DateTime> ResultatBokatDatum { get; set; }
        public Nullable<short> ResultatBokatRedovisnAr { get; set; }
        public Nullable<int> ResultatBokatVerNr { get; set; }
        public string RowCreatedBy { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string RowUpdatedBy { get; set; }
        public string RowUpdatedCols { get; set; }
        public Nullable<System.DateTime> RowUpdatedDt { get; set; }
        public Nullable<short> SenVinstAvraknAr { get; set; }
        public Nullable<System.DateTime> SenVinstAvraknDat { get; set; }
        public Nullable<short> SenVinstAvraknPer { get; set; }
        public string TjansteKonto { get; set; }
        public string ValKod { get; set; }
        public decimal ValKurs { get; set; }
        public Nullable<int> Vernr { get; set; }
        public string WebAccountMark { get; set; }
        public decimal q_prj_prisperh { get; set; }
        public string q_prj_valkodfakt { get; set; }
        public string CreateEx { get; set; }
        public Nullable<short> ICTRuleNumber { get; set; }
        public Nullable<short> IntrnCoNoOrigin { get; set; }
        public string PrjAccountCheck { get; set; }
        public string q_prj_invoice_layout { get; set; }
        public string q_prj_subproject_entry { get; set; }
        public Nullable<short> ActvyGrpsId { get; set; }
        public decimal AllcdTime { get; set; }
        public string AttestSign { get; set; }
        public Nullable<short> AttKedja { get; set; }
        public decimal ComplPercent { get; set; }
        public string EstimatorOffNr { get; set; }
        public Nullable<short> EstimatorOffRadNr { get; set; }
        public string EstimatorProject { get; set; }
        public string MandPlanActvy { get; set; }
        public string MasterProject { get; set; }
        public Nullable<int> NoOfRows { get; set; }
        public Nullable<int> OffRadNr { get; set; }
        public string PrjCust { get; set; }
        public Nullable<short> PrjOwnUseId { get; set; }
        public decimal ProjCostExp { get; set; }
        public decimal ProjCostTime { get; set; }
        public decimal ProjectCostBCU { get; set; }
        public decimal ProjectCostFCU { get; set; }
        public decimal ProjectRevenueBCU { get; set; }
        public decimal ProjectRevenueFCU { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public Nullable<System.DateTime> RowCreatedUTCDT { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public double TotPBeranttim { get; set; }
        public decimal TotProjCostExp { get; set; }
        public decimal TotProjCostTime { get; set; }
        public decimal TotProjKost { get; set; }
        public double TotProjKvarTid { get; set; }
        public double TotProjNerlTid { get; set; }
    }
}
