//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_ex_preinsert
    {
        public string PersSign2 { get; set; }
        public string FtgNr { get; set; }
        public string ProjCode { get; set; }
        public System.DateTime ExLevDat { get; set; }
        public string ArtNr { get; set; }
        public double q_ex_antalanstalld { get; set; }
        public decimal vb_pris { get; set; }
        public Nullable<decimal> q_ex_ingmoms { get; set; }
        public string Editint { get; set; }
        public string EditExt { get; set; }
        public string q_ex_guiid { get; set; }
        public Nullable<int> q_reimburse_employee { get; set; }
        public Nullable<int> foretagkod { get; set; }
        public string createdby { get; set; }
        public string valutakod { get; set; }
        public Nullable<double> valutakurs { get; set; }
    }
}
