//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_hrp_preinsert
    {
        public string q_hrp_guiid { get; set; }
        public string ftgnr { get; set; }
        public string projcode { get; set; }
        public System.DateTime regdate { get; set; }
        public string perssign { get; set; }
        public string subproject { get; set; }
        public string editext { get; set; }
        public string editint { get; set; }
        public double usedtime { get; set; }
        public double invoicedtime { get; set; }
        public Nullable<int> delayinvoice { get; set; }
        public Nullable<int> foretagkod { get; set; }
        public Nullable<int> record_ok { get; set; }
    }
}
