//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy2
    {
        public string AnmodanMark { get; set; }
        public Nullable<short> AnskaffningsSatt { get; set; }
        public string ArtProdKonto { get; set; }
        public Nullable<decimal> attestlimit { get; set; }
        public string authorizecode { get; set; }
        public string AutoOrderEnding { get; set; }
        public string autopris { get; set; }
        public string AutoRegel { get; set; }
        public string AutoRegelS { get; set; }
        public Nullable<short> Belaggningskod { get; set; }
        public Nullable<int> Buntnr { get; set; }
        public string CashBalanceTemplate { get; set; }
        public Nullable<short> CashConfigCode { get; set; }
        public string CCU { get; set; }
        public Nullable<short> CheckBestGen { get; set; }
        public string CRM { get; set; }
        public string CTI { get; set; }
        public string DbLoginId { get; set; }
        public string dbserver { get; set; }
        public string DebugMsg { get; set; }
        public string DefAnswer { get; set; }
        public Nullable<short> DefForetagKod { get; set; }
        public string DefVerRevDate { get; set; }
        public string DokDir { get; set; }
        public string DokDirCheckOut { get; set; }
        public string EDM { get; set; }
        public Nullable<short> FakturaNrGrupp { get; set; }
        public Nullable<short> FakturerareKod { get; set; }
        public short ForetagKod { get; set; }
        public string FtgNr { get; set; }
        public Nullable<short> GoToOrderEnding1 { get; set; }
        public Nullable<short> GoToOrderEnding2 { get; set; }
        public Nullable<short> GoToOrderEnding3 { get; set; }
        public Nullable<short> grupp { get; set; }
        public string InkHandl { get; set; }
        public string InvoiceAllowed { get; set; }
        public string KodGruppSignatur { get; set; }
        public string KolliNrAlfaPrefix { get; set; }
        public string KontRegKod { get; set; }
        public string KstInterimsBokning { get; set; }
        public string KstReskSaldo { get; set; }
        public string KundNrKontant { get; set; }
        public string LagStalle { get; set; }
        public Nullable<int> LastBuntnr { get; set; }
        public Nullable<short> manver { get; set; }
        public Nullable<int> Maxbuntnr { get; set; }
        public string NE_PlanAnsv { get; set; }
        public string OpenClosedClaim { get; set; }
        public Nullable<short> OrdStat { get; set; }
        public Nullable<short> OrdTyp { get; set; }
        public Nullable<short> Period { get; set; }
        public string PersSign { get; set; }
        public string PlanAnsv { get; set; }
        public string POS { get; set; }
        public string Rapportor { get; set; }
        public string ReadOnly { get; set; }
        public string ReceiptTemplate { get; set; }
        public Nullable<short> Redovisnar { get; set; }
        public System.DateTime RegDat { get; set; }
        public string RespNamn { get; set; }
        public string RowCreatedBy { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string RowUpdatedBy { get; set; }
        public Nullable<System.DateTime> RowUpdatedDt { get; set; }
        public string SaldoOnLine { get; set; }
        public string Saljare { get; set; }
        public string SamInkopMark { get; set; }
        public string ShowFrcstInPlan { get; set; }
        public string ShowOrderRadHistorik { get; set; }
        public Nullable<short> ShowOrderRadStatus { get; set; }
        public Nullable<short> SprakKod { get; set; }
        public Nullable<short> StartInvoicePgm { get; set; }
        public string SysAdmAllowed { get; set; }
        public string TiOnLine { get; set; }
        public string UtskrDokSparr { get; set; }
        public string ValidToUse { get; set; }
        public string VerNrGrupp { get; set; }
        public Nullable<short> VisaFromRedovisnAr { get; set; }
        public Nullable<short> VisaOStockFromOrdStat { get; set; }
        public Nullable<short> VisaOStockTomOrdStat { get; set; }
        public Nullable<short> VisaTomRedovisnAr { get; set; }
        public string WarningAtDeliver { get; set; }
        public string Wflw { get; set; }
        public string YndEmailAddr { get; set; }
        public Nullable<short> AdjustMinutes2GetLocalTime { get; set; }
        public string BusinessUnit { get; set; }
        public Nullable<short> CDD_From_Lang { get; set; }
        public string DispCheckInOrderStore { get; set; }
        public string KreditMemoUtfardare { get; set; }
        public string OptItemsInOrderStore { get; set; }
        public string TA_allowed { get; set; }
        public string TA_FileSuffix { get; set; }
        public Nullable<short> Ta_SysPid { get; set; }
        public string VisibleInOffice { get; set; }
        public string WMS { get; set; }
        public string q_sy2_employeenr { get; set; }
        public string CreditWarningAtPicking { get; set; }
        public Nullable<short> DefaultRole { get; set; }
        public string LogtradeUserId { get; set; }
        public string LogtradeUserPW { get; set; }
        public Nullable<short> MaxNoOfClients { get; set; }
        public Nullable<short> OfficeUserRoleType { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public Nullable<System.DateTime> RowCreatedUTCDT { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> SeqNoOrderShuffle { get; set; }
        public string ShowPDMMsgs { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public string ViewAllTimeReport { get; set; }
        public string WarningAtReceiveDeliv { get; set; }
        public string createtempmo { get; set; }
        public string invcreprintallwd { get; set; }
    }
}
