//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysp
    {
        public string CancelSQLProcedure { get; set; }
        public string DBLogInSign { get; set; }
        public Nullable<short> ForetagKod { get; set; }
        public Nullable<short> Grupp { get; set; }
        public string InfoFromSQLProcedure { get; set; }
        public string JeevesPgmId { get; set; }
        public string ObjectName { get; set; }
        public string PersSign { get; set; }
        public int ProcIdDBLib { get; set; }
        public int ProcIdDBLibPgmId { get; set; }
        public int RadPos { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public System.DateTime RowUpdatedDt { get; set; }
        public int spid { get; set; }
        public int spidpgm { get; set; }
        public Nullable<short> SprakKod { get; set; }
        public string x255 { get; set; }
        public string ClientSessionGUID_Str { get; set; }
        public string DebugMsg { get; set; }
        public Nullable<short> Ict_Level { get; set; }
        public short No_Trigger_Exec { get; set; }
        public Nullable<short> Repl_Level { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public Nullable<System.DateTime> RowCreatedUTCDT { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public short TimeZoneUTCOffset { get; set; }
    }
}
