//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_teammanager_options
    {
        public string perssign { get; set; }
        public string ftgnr { get; set; }
        public Nullable<int> prelfaktura { get; set; }
        public string customerresponsible { get; set; }
    }
}
