//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_getdefinition
    {
        public string ftgnr { get; set; }
        public string ftgnamn { get; set; }
        public string projcode { get; set; }
        public string projdescr { get; set; }
        public string aktivitet { get; set; }
        public string strdatetimehr { get; set; }
        public string AssignmentStatus { get; set; }
        public string ProjectStatus { get; set; }
        public string SubProjectStatus { get; set; }
        public string SubprojectEntry { get; set; }
    }
}
